spring.application.name=mcis-security-system

server.port=8080

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/mcis_db
spring.datasource.username=postgres
spring.datasource.password=Nilesh@2772

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false

# Keycloak OAuth2 Client
spring.security.oauth2.client.registration.keycloak.client-id=mcis-security-system
spring.security.oauth2.client.registration.keycloak.client-secret=Jxn78yRTDYDa46rjtboh3NI1PN5jYWfa
spring.security.oauth2.client.registration.keycloak.scope=openid,profile,email
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:9090/realms/MCIS-Realm